version: '2'

services:

  web:
    image: nginx:1.13.3
    links:
      - "php-fpm"
    ports:
      - "3099:80"
    volumes:
      - "./:/var/www"
      - "./docker/config/nginx.conf:/etc/nginx/conf.d/default.conf"

  php-fpm:
    build:
      context: ./docker/php/build
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    env_file: .env
    volumes:
      - "./:/var/www"

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - '3080:80'